class ParsedScaleItem {
  final String rawBarcode;
  final String prefix;
  final String plu;
  final double? weightInGrams;
  final double? weightInKg;
  final double? priceInRupees;
  final bool isWeightEmbedded;

  const ParsedScaleItem({
    required this.rawBarcode,
    required this.prefix,
    required this.plu,
    this.weightInGrams,
    this.weightInKg,
    this.priceInRupees,
    required this.isWeightEmbedded,
  });

  @override
  String toString() =>
      'ParsedScaleItem(PLU: $plu, Weight: ${weightInKg?.toStringAsFixed(3)} kg, Price: Rs. ${priceInRupees?.toStringAsFixed(2)})';
}

/// Decodes GS1 variable-measure barcodes (EAN-13 Prefixes 20-29) generated by
/// electronic weighing scales (CAS, Digi, Rongta, Mettler Toledo).
class ScaleBarcodeParser {
  /// Parses raw 13-digit barcode string into PLU and Weight or Price
  static ParsedScaleItem? parse(String rawCode) {
    final cleaned = rawCode.trim();
    if (cleaned.length != 13) return null;

    final prefix = cleaned.substring(0, 2);

    // Standard GS1 Restricted In-Store Circulation Prefixes:
    // 20 & 21: Typically Weight-Embedded (e.g., grams)
    // 22 & 28: Typically Price-Embedded (e.g., paisas/rupees)
    if (['20', '21', '22', '28'].contains(prefix)) {
      final plu = cleaned.substring(2, 7);
      final rawValue = int.tryParse(cleaned.substring(7, 12));
      if (rawValue == null) return null;

      final isWeight = prefix == '20' || prefix == '21';

      return ParsedScaleItem(
        rawBarcode: cleaned,
        prefix: prefix,
        plu: plu,
        weightInGrams: isWeight ? rawValue.toDouble() : null,
        weightInKg: isWeight ? rawValue / 1000.0 : null,
        priceInRupees: !isWeight ? rawValue / 100.0 : null,
        isWeightEmbedded: isWeight,
      );
    }
    return null;
  }
}
